plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    // mavens for Create Fabric and dependencies
    maven { url = "https://maven.createmod.net/" }
    maven { url = "https://mvn.devos.one/releases" }
    maven { url = "https://mvn.devos.one/snapshots" }
    maven { url = "https://maven.tterrag.com/" }
    maven { url = "https://maven.jamieswhiteshirt.com/libs-release" }
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" }

    maven { // Fabric ASM for Porting Lib
        url = "https://jitpack.io/"
        content { includeGroupAndSubgroups("com.github") }
    }

    maven { url = "https://maven.blamejared.com" } // JEI
    maven { url = "https://maven.terraformersmc.com/releases" } // Mod Menu, EMI
}

configurations.configureEach {
    resolutionStrategy {
        // make sure the desired version of loader is used. Sometimes old versions are pulled in transitively.
        force("net.fabricmc:fabric-loader:$fabric_loader_version")
    }
}

dependencies {
    modImplementation("net.fabricmc:fabric-loader:$fabric_loader_version")
    common(project(path: ":common", configuration: "namedElements")) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')

    // dependencies
    modImplementation("net.fabricmc.fabric-api:fabric-api:$fabric_api_version")

    // Create - dependencies are added transitively
    modImplementation("com.simibubi.create:create-fabric:${create_fabric_version}") // Create
}

processResources {
    // set up properties for filling into metadata
    Map<String, Object> properties = [
            "version": version,
            "fabric_loader_version": fabric_loader_version,
            "fabric_api_version": fabric_api_version,
            "minecraft_version": minecraft_version,
            "create_version": create_fabric_version // on fabric, use the entire version, unlike forge
    ]
    inputs.properties(properties)

    filesMatching("fabric.mod.json") {
        expand properties
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
