org.gradle.jvmargs = -Xmx2048M

mod_version = 0.4.8
minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

# Create - Forge
# https://wiki.createmod.net/developers/
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67

# Create - Fabric
# https://modrinth.com/mod/create-fabric/versions
create_fabric_version = 6.0.8.1+build.1744-mc1.20.1

# Mod Menu - https://modrinth.com/mod/modmenu/versions
modmenu_version = 7.2.2
# LazyDFU - https://modrinth.com/mod/lazydfu/versions
lazydfu_version = 0.1.3

archives_base_name = missions
maven_group = com.kryeit

# Fabric
# https://fabricmc.net/develop/
fabric_loader_version=0.19.2
fabric_api_version=0.116.12+1.21.1
neoforge_version=21.1.215
